from typing import TYPE_CHECKING, Any, Generic, TypeVar, Self

_T = TypeVar("_T", bound=object)


class Query(Generic[_T]):
    __model: type[_T]
    __path_csv: str
    __limit: int | None
    __offset: int | None
    __order_by: str | None
    __filters: dict[str, Any] | None

    def __init__(self, model: type[_T], path_csv: str) -> None: ...

    def where(self, **filters: Any) -> Self: ...

    def limit(self, num: int) -> Self: ...

    def offset(self, num: int) -> Self: ...

    def order_by(self, attribute: str) -> Self: ...

    def get_all(self) -> list[_T]: ...

    def set_filters(self) -> list[_T]: ...

    def all(self) -> list[_T]: ...

    def first(self) -> _T | None: ...

    def exists(self) -> bool: ...

    def count(self) -> int: ...

    def delete(self) -> int: ...

    def update(self, **updates: Any) -> int: ...
