from typing import TypeVar, overload, Unpack, TYPE_CHECKING, Literal, Generic, Self

T = TypeVar('T', bound=object)

class Query(Generic[T]):
  __model: type[T]
  __path_csv: str
  __limit: int | None
  __offset: int | None
  __order_by: str | None
  __filters: dict[str, object] | None

  def where(self, **filters: object) -> 'Query[T]': ...

  def update(self, **values: object) -> int: ...

  def order_by(self, attribute: list[str]) -> 'Query[T]': ...

  def __init__(self, model: type[T], path_csv: str) -> None: ...

  def limit(self, num: int) -> Self: ...

  def offset(self, num: int) -> Self: ...

  def get_all(self) -> list[T]: ...

  def set_filters(self) -> list[T]: ...

  def all(self) -> list[T]: ...

  def first(self) -> T | None: ...

  def exists(self) -> bool: ...

  def count(self) -> int: ...

  def delete(self) -> int: ...
